### ISSUE TITLE
Pie chart does not work with one "point"

### ISSUE THREAD

**Issue by aibeke** [AnyChart/migration-tool#1]
Pie chart does not work with one "point".
I modified file "[14-2D-Pie-Chart-Outside-Labels-with-connectors.html](http://savetext.ru/0fH8rM8W)" from samples.

**Comment by RomanLubushkin** [comment]
Fixed with @aibekepull [pull request](https://github.com/AnyChart/anychart-v6-to-v7-migration-tool/pull/2)
